spring:
  application:
    name: wow-firehose-analytics
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: wow-firehose-analytics
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest

spring.autoconfigure.exclude: >
  org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,
  org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,
  org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  endpoint:
    prometheus:
      enabled: true

server:
  port: 8082
  address: 0.0.0.0

app:
  topic: wow.player.metrics.v1
logging:
  level:
    org.springframework.kafka: DEBUG
    org.apache.kafka: WARN