global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'spring-apps'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - '172.28.7.52:8081'  # producer
          - '172.28.7.52:8082'  # consumer

  - job_name: 'redpanda'
    metrics_path: /metrics
    static_configs:
      - targets: ['redpanda:9644']
